https://hub.docker.com/layers/h2oairelease/h2oai-h2ogpt-runtime/v0.2.0-591/images/sha256-7981a0837e6847d30538add4a0cf6ddabeece2cd0b60c9bba0d309d925fd688d
https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md
